mod tempmod is 
  protecting CONSTR .
  ops T0 T1 T2 T3 T4 T5 T6 T7 T8 T9 T10 T11 T12 T13 T14 T15 T16 T17 T18 T19 : -> VarType .
  ops T?0 T?1 T?2 T?3 T?4 T?5 T?6 T?7 T?8 T?9 T?10 T?11 T?12 T?13 T?14 T?15 T?16 T?17 T?18 T?19 : -> BoundVarType .
  op c : -> Disj .

  eq c = 
((T1 <= list< int + str >) /\ (T1 <= list< top > + bytes + dict< top, top > + bytearray + range + memoryview + str + tuple< top > + frozenset< top > + set< top >)) .

endm