"""
Simple test stub file for testing the stub ingestor.
Contains simplified versions of int, float, a custom class, and a protocol.
"""

from typing import Protocol, Self


class Cint:
    pass


class Cfloat:
    pass


class int:
    """Simplified int class with basic arithmetic operations."""
    
    def __init__(self, value: int) -> None: ...
    def __add__(self, other: int) -> int: ...
    def __sub__(self, other: int) -> int: ...
    def __mul__(self, other: int) -> int: ...
    def __neg__(self) -> int: ...
    def __pos__(self) -> int: ...
    def __abs__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: int) -> bool: ...
    def __str__(self) -> str: ...
    def hex(self) -> str: ...


class float:
    """Simplified float class with basic arithmetic operations."""
    
    def __init__(self, value: float) -> None: ...
    def __add__(self, other: float) -> float: ...
    def __sub__(self, other: float) -> float: ...
    def __mul__(self, other: float) -> float: ...
    def __neg__(self) -> float: ...
    def __pos__(self) -> float: ...
    def __abs__(self) -> float: ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: float) -> bool: ...
    def __str__(self) -> str: ...
    

class MyNumber:
    """
    A user-defined custom class that mimics numeric behavior.
    Contains two methods common to both int and float: __add__ and __neg__.
    """
    
    value: int
    
    def __init__(self, value: int) -> None: ...
    def __add__(self, other: int) -> int: ...
    def __neg__(self) -> int: ...


class SupportsNeg(Protocol):
    """
    A protocol describing any class that implements the __neg__ method.
    Both int and float implement this method.
    """
    
    def __neg__(self) -> int: ...


class SupportsSelfMul(Protocol):
    def __mul__(self, other: Self) -> Self: ...
