mod tempmod is 
  protecting CONSTR .
  ops T0 T1 T2 T3 T4 T5 T6 T7 T8 T9 T10 T11 T12 T13 T14 T15 T16 T17 T18 T19 : -> VarType .
  ops T?0 T?1 T?2 T?3 T?4 T?5 T?6 T?7 T?8 T?9 T?10 T?11 T?12 T?13 T?14 T?15 T?16 T?17 T?18 T?19 : -> BoundVarType .
  ops c1 c2 c3 c4 c5 c6 c7 c8 c9 c10 c11 c12 c13 c14 c15 c16 c17 c18 c19 c20 c21 c22 c23 c24 c25 c26 c27 c28 c29 c30 c31 c32 c33 c34 c35 c36 c37 c38 c39 c40 c41 c42 c43 : -> Disj .

  eq c1 = (T1 <= list< int + float >) /\ (T1 <= list< T?0 + int + float >) .
  eq c2 = (T1 <= int + float + str) /\ (T1 <= str + int + complex) .
  eq c3 = (T1 <= int + float + list< set< str > >) /\ (T1 <= list< set< str + int > > + complex) .
  eq c4 = (T1 <= int + float + set< str >) /\ (T1 <= set< str + int > + complex) .
  eq c5 = (T1 <= int + float + list< str >) /\ (T1 <= list< str + int > + complex) .
  eq c6 = (T1 <= int + float + list< set< str > >) /\ (T1 <= list< set< str + int > > + complex) .
  eq c7 = (T1 <= list< T3 + T4 >) /\ (T1 <= list< T?0 >) .
  eq c8 = (T1 <= list< set< T3 + T4 > >) /\ (T1 <= list< set< T?0 > >) .
  eq c9 = (T1 <= list< set< T3 + T4 > >) /\ (T1 <= list< set< T?0 > > + int) .
  eq c10 = (T1 <= list< int + float >) /\ (T1 <= list< int > + int) .
  eq c11 = (T1 <= list< int + float >) /\ (T1 <= list< int >) .
  eq c12 = (T1 <= list< T3 + T4 > + int) /\ (T1 <= int + list< T?0 >) .
  eq c13 = (T1 <= list< T3 + T4 > + float + int) /\ (T1 <= int + list< T?0 >) .
  eq c14 = (T1 <= T?0) /\ (T1 <= int + float) /\ (T2 <= T?1) /\ (T2 <= complex) .
  eq c15 = (T1 <= dict< T?0, T?1 >) /\ (T1 <= dict< int + float, T2 >) .
  eq c16 = (T1 <= int + dict< T?0, T?1 >) /\ (T1 <= dict< int + float, T2 >) .
  eq c17 = (T1 <= int + float) /\ (T1 <= dict< top, top > + bytes + str + frozenset< top > + bytearray + tuple< top > + list< top > + memoryview + range + set< top >) .
  eq c18 = (T1 <= int) \/ (T1 <= float) .
  eq c19 = ((T1 <= int + float) /\ (T1 <= dict< top, top > + bytes + str + frozenset< top >)) \/ ((T1 <= int + float) /\ (T1 <= bytearray + tuple< top > + list< top > + memoryview + range + set< top >)) .
  eq c20 = ((T1 <= int + float) /\ (T1 <= dict< top, top > + bytes + str + int + frozenset< top >)) \/ ((T1 <= int + float) /\ (T1 <= bytearray + tuple< top > + list< top > + memoryview + range + set< top >)) .
  eq c21 = ((T1 <= int + float) /\ (T1 <= dict< top, top > + bytes + str + int + frozenset< top > + bytearray + tuple< top > + list< top > + memoryview + range + set< top >)) .
  eq c22 = (T1 <= dict< top, top > + bytes + str + int + frozenset< top > + bytearray + tuple< top > + list< top > + memoryview + range + set< top >) .
  eq c23 = (T1 <= int + float) /\ (T1 <= set< top > + memoryview + range + str + frozenset< top > + tuple< top > + bytearray + dict< top, top > + list< top > + bytes) .
  eq c24 = (T1 <= int + float) /\ (T1 <= str + complex) .
  eq c25 = (T1 <= int + float) /\ (T2 <= str + complex) .
  eq c26 = (T1 <= list< int + float >) /\ (T2 <= list< str + complex >) .
  eq c27 = (T1 <= set< int + float >) /\ (T2 <= set< str + complex >) .
  eq c28 = (T1 <= dict< int + float, str + complex >) /\ (T2 <= dict< str, bytes + bytearray >) .
  eq c29 = (T1 <= list< int >) /\ (T2 <= list< str + complex >) .
  eq c30 = (T1 <= int + float) /\ (T1 <= str) .
  eq c31 = (T1 <= list< int + float >) /\ (T2 <= dict< int, str + complex >) .
  eq c32 = (T1 <= dict< int, str + complex > ) .
  eq c33 = (T1 <= list< int + float >) /\ (T2 <= dict< int + float, str + complex >) .
  eq c34 = (T4 <= bytes) /\ (T4 <= list< T1 + T2 >) .
  eq c35 = (T4 <= bytes) /\ (T5 <= memoryview + bytes + bytearray) /\ (T4 <= list< T1 + T2 >) /\ (T5 <= list< T3 >) .
  eq c36 = (T5 <= list< T3 >) /\ (T5 <= memoryview + bytes + bytearray) .
  eq c37 = (T1 <= list< int >) /\ (T1 <= list< str + complex >) .
  eq c38 = (T1 <= list< int + str >) /\ (T1 <= list< str + complex >) .
  eq c39 = (T1 <= list< int + str >) /\ (T1 <= list< str + complex >) /\ (T2 <= int + float) /\ (T2 <= float + str) .
  eq c40 = (T1 <= dict< int, str + complex >) /\ (T1 <= dict< int + float, str >) .
  eq c41 = (T1 <= list< int >) /\ (T1 <= list< float + T1 >) .
  eq c42 = (T1 <= list< int > + int) /\ (T1 <= list< int + float + T1 > + int + float) .
  eq c43 = (T1 <= list< int > + int) \/ (T1 <= list< int + float + T1 > + int + float) .

endm